name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        # Login to DockerHub Registry
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag unfollowersdetector:$(date +%s)
      
      
    - name: Push the Docker image
      run: docker tag unfollowersdetector:$(date +%s) ${{ secrets.DOCKERHUB_USERNAME }}/unfollowersdetector:$(date +%s)
