name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
  
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
  build_and_push:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Build the Docker image
        run:  docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/unfollowersdetector:$(date +%s) -t ${{ secrets.DOCKERHUB_USERNAME }}/unfollowersdetector:latest .  
      
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/unfollowersdetector:latest
          
  
