name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_push:

    runs-on: ubuntu-latest
    
    steps:

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD  }}
 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag unfollowersdetector:$(date +%s)
      
      
    - name: Push the Docker image
      run: docker tag unfollowersdetector:$(date +%s) ${{ secrets.DOCKERHUB_USERNAME }}/unfollowersdetector:$(date +%s)
