name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build the Docker image
        run: docker build . --file Dockerfile
      
      
      - name: Push the Docker image
        run: docker tag unfollowersdetector:$(date +%s) ${{ secrets.DOCKERHUB_USERNAME }}/unfollowersdetector:$(date +%s) && docker push ${{ secrets.DOCKERHUB_TOKEN }}/unfollowersdetector:$(date +%s)
